apiVersion: v1
kind: Service
metadata:
  name: minio
  labels:
    io.kompose.service: minio
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.36.0 (ae2a39403)
spec:
  type: {{ .Values.minio.type }}
  selector:
    io.kompose.service: minio
  ports:
  {{- .Values.minio.ports | toYaml | nindent 2 }}
