apiVersion: v1
kind: Service
metadata:
  name: mwdb
  labels:
    io.kompose.service: mwdb
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.36.0 (ae2a39403)
spec:
  type: {{ .Values.mwdb.type }}
  selector:
    io.kompose.service: mwdb
  ports:
  {{- .Values.mwdb.ports | toYaml | nindent 2 }}
