apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    io.kompose.service: postgres
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.36.0 (ae2a39403)
spec:
  type: {{ .Values.postgres.type }}
  selector:
    io.kompose.service: postgres
  ports:
  {{- .Values.postgres.ports | toYaml | nindent 2 }}
