apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    io.kompose.service: redis
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.36.0 (ae2a39403)
spec:
  type: {{ .Values.redis.type }}
  selector:
    io.kompose.service: redis
  ports:
  {{- .Values.redis.ports | toYaml | nindent 2 }}
