apiVersion: v1
kind: Service
metadata:
  name: mwdb-web
  labels:
    io.kompose.service: mwdb-web
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.36.0 (ae2a39403)
spec:
  type: {{ .Values.mwdbWeb.type }}
  selector:
    io.kompose.service: mwdb-web
  ports:
  {{- .Values.mwdbWeb.ports | toYaml | nindent 2 }}
